version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "db_name"
    ports:
      - "5432:5432"
  web:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    depends_on:
      - db